base_url = "https://memorage.org"
title = "Memorage"
description = "Memorage is a peer to peer backup service."

default_language = "en"
compile_sass = true
build_search_index = true
minify_html = true
theme = "adidoks"
taxonomies = [
  { name = "authors" },
]

[search]
include_title = true
include_description = true
include_content = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
author = "Klim Tsoutsman"
github = "https://github.com/memorage"
email = "klim@memorage.org"
is_netlify = true
language_code = "en-US"
theme_color = "#fff"
timeformat = "%Y-%m-%d %H:%M:%S" # e.g. 2021-05-01 09:19:42
timezone = "UTC"
